stream {
        upstream stream_psql {
                least_conn;
                server 10.0.0.9:5432;
        }

        upstream stream_mongo {
                least_conn;
                server 10.0.0.9:27017;
        }

        server {
                listen 35032;
                proxy_pass stream_psql;
                proxy_timeout 3s;
                proxy_connect_timeout 3s;
        }

        server {
                listen 35017;
                proxy_pass stream_mongo;
                proxy_timeout 3s;
                proxy_connect_timeout 3s;
        }
}